# fly.toml file generated for morning-bird-7081 on 2023-04-12T21:36:50-04:00

app = "morning-bird-7081"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "registry.fly.io/morning-bird-7081:latest"

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "2s"
    method = "get"
    path = "/docs"
    protocol = "http"
    timeout = 2000
    restart_limit = 6
