name: Continuous Integration

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - run: sbt test

      - name: Compress target directories
        run: tar cf targets.tar target project/target

      - name: Upload target directories
        uses: actions/upload-artifact@v3
        with:
          name: target-ubuntu-latest-temurin-17
          path: targets.tar

  deploy:
    needs: build
    name: Deploy app
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
      - run: sbt "Docker / stage"
      - run: flyctl deploy --dockerfile target/docker/stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
